- jim-aio.c
I/O errors contain "%ld", because channel names are not formatted.
> Bug fix - channel names are not formatted

- jim.c
- jim.h
- jim_tcl.txt
- tests/expr-new.test
- tests/string.test
- tests/while.test
* named boolean values in `expr` are internally converted to int
* named constants are lower-case only
> Boolean contstants in expr, `string is boolean` classification

- jim-interp.c
GCC complains about possible truncation from snprintf()
jim-interp.c: In function ‘JimInterpCommand’:
jim-interp.c:164:46: warning: ‘%ld’ directive output may be
truncated writing between 1 and 20 bytes into a region of size
19 [-Wformat-truncation=]
snprintf(buf, sizeof(buf), "interp.handle%ld", Jim_GetId(interp));
^~~
jim-interp.c:164:32: note: directive argument in the range
[-9223372036854775807, 9223372036854775807]
snprintf(buf, sizeof(buf), "interp.handle%ld", Jim_GetId(interp));
^~~~~~~~~~~~~~~~~~
jim-interp.c:164:5: note: ‘snprintf’ output between 15 and 34 bytes
into a destination of size 32
snprintf(buf, sizeof(buf), "interp.handle%ld", Jim_GetId(interp));
^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Signed-off-by: Antonio Borneo <borneo.antonio@gmail.com>
> jim-interp.c: fix compile warning with GCC 8.1.1

- jim-json.c
- jim_tcl.txt
- tests/json.test
This is my implementation of `-index` for `json::decode`.  I have decided not to switch the schema to an index dict format because that would lead to something like `{mixed num bool str}` becoming `{SPECIAL_TYPE_KEY mixed 0 num 1 bool 2 str}` and then for use consistency `{obj key num key2 str}` becoming `{SPECIAL_TYPE_KEY obj key num key2 str}`.  No matter what you chose for `SPECIAL_TYPE_KEY`, in the latter case it could conflict with a key given by the user.  This would be a potential source of errors and in some cases security problems.
> json: implement -index option

- tests/aio.test
- tests/socket.test
- tests/tty.test
In some cases they differ from what you get when you build Jim on a GNU libc system.
> Match musl error messages in aio, socket, and tty tests

- .gitignore
Commit aa4427dee716 ("Add pkg-config support: jimtcl.pc") adds the
build time file jimtcl.pc
Commit 630df0da46f4 ("Update autosetup to v0.6.8") adds running
make-template on tests/Makefile.in, producing tests/Makefile
Add both jimtcl.pc and tests/Makefile to .gitignore
Signed-off-by: Antonio Borneo <borneo.antonio@gmail.com>
> update .gitignore adding jimtcl.pc and tests/Makefile

- jim.c
- jim_tcl.txt
- tests/expr-base.test
This is a feature coming in Tcl 8.7.  Compared to other Tcl 8.7 features that could work in Jim Tcl, it is particularly difficult to shim.  [TIP472](https://core.tcl-lang.org/tips/doc/trunk/tip/472.md).
> TIP 472: Add Support for 0d Radix Prefix to Integer Literals

- jim.c
- jim_tcl.txt
- tests/expr-new.test
This implements the operators `lt`, `gt`, `le`, `ge`.  [TIP 461](https://core.tcl-lang.org/tips/doc/trunk/tip/461.md).
> TIP 461: Separate Numeric and String Comparison Operators

- jim.c
- tests/expr.test
The unary `!` in Tcl 8 expressions works with all booleans: 0, 1, `true`, `false`,`yes`, `no`,`on`, `off`.  This PR implements the same capability in Jim.
> Make unary "!" work with non-int booleans

- .gitignore
- Makefile.in
When building in-tree, the generated file is not ignored and the
tree appears as dirty.
Add the generated file to .gitignore.
Signed-off-by: Antonio Borneo <borneo.antonio@gmail.com>
> .gitignore: add generated file /examples.api/Makefile

- utf8.c
E.g., see the hourglass character U+231B closing the range at line 1111 of the bundled EastAsianWidth.txt:
https://github.com/msteveb/jimtcl/blob/3bf391ebe1a87c1fd0fc064254ef40976dff06f9/EastAsianWidth.txt#L1111
> Unicode ranges are closed intervals

- auto.def
- jimiocompat.h
Mostly we need to specifically target WinXP.
Also silence deprecation warnings.
And fix the confusion about _stat64 vs __stat64
Fixes #219
Signed-off-by: Steve Bennett <steveb@workware.net.au>
> build: win32: Fix build with tdm-gcc10.3

- configure.ac
Jimtcl dropped the file configure.ac with commit 2ffa2eee88f3 ("Remove obsolete configure.ac") in 2011, but this caused a build failure when jimtcl is used as submodule by OpenOCD. Instead of fixing the obsoleted path in OpenOCD's configure.ac, a patch to add a dummy configure.ac was merged in jimtcl with commit 142edb4e35a90 ("Re-add a dummy configure.ac for automake").
The resulting setup still has issues, as running 'autoremake -f' in OpenOCD folder causes autoconf to replace jimtcl configure file with an incorrect file generated from the dummy configure.ac .
OpenOCD release v0.12.0 includes a fix that makes useless the dummy configure.ac in jimtcl: https://review.openocd.org/7437/ ("configure.ac: fix check for jimtcl submodule").
Drop the dummy configure.ac .
Signed-off-by: Antonio …
> Drop the dummy file configure.ac

- jim.c
The Appveyor build generates this otherwise:
```
In function 'Jim_WhileCoreCommand',
inlined from 'Jim_WhileCoreCommand' at jim.c:12096:12:
jim.c:12109:12: warning: 'boolean' may be used uninitialized [-Wmaybe-uninitialized]
12109 |         if (!boolean)
|            ^
jim.c: In function 'Jim_WhileCoreCommand':
jim.c:12105:13: note: 'boolean' was declared here
12105 |         int boolean, retval;
|             ^~~~~~~
```
> Silence compiler warning

- Makefile.in
json decoder is available since jimtcl 0.79, but the Makefile does not remove the related object files during 'make clean'.
Add jsmn/*.o in the list of files to remove during 'make clean'.
> build: remove jsmn/*.o on clean

- examples.api/jim_command.c
- examples.api/jim_list.c
- examples.api/jim_obj.c
- examples.api/jim_return.c
The macro JIM_EMBEDDED was required to be defined before including jim.h in applications that embed jimtcl.
This requirement has been dropped in 2010 with commit 2d8564100c86 ("Documentation updates") but it's use has remained for longer and it even re-appeared later in the examples.api.
Drop last instances of JIM_EMBEDDED.
> examples.api: drop last JIM_EMBEDDED definitions

- jim.c
- jim_tcl.txt
- tests/breakcontinue.test
- tests/jim.test
Experimental proposal for multi-level loop break, continue.
```
loop i 5 {
loop j 6 {
;# This breaks out of both loops
break 2
}
}
```
Comments welcome
> core: support multi-level while, break from loops

- jim.c
- jim.h
- jim_tcl.txt
- tests/procstatic.test
This is an experimental feature that allows for lexical closures in Jim Tcl by allowing procs (and lambdas) to capture variables by reference rather than by value. e.g.
```
set a 5
proc b {} {&a} {
incr a
}
b
```
Now a is 6 because b captured a by reference instead of by value
> core: add support for proc static variables by reference

- jim.c
- jim.h
- tests/jim.test
And allow current source file to be set
Fixes: #268
> info script: return real current source file

- jim-sdl.c
Here's a very small patch to fix the ordering of the SDL `text` subcommand help, which was not what was being parsed. The string to be drawn is in fact the first argument. 
In first looking at this, I thought it might make sense to change the _parsing_ to match the help text, but that's more complicated and is unlike any other SDL subcommand in that it features multiple numeric arguments _and_ a string. Due to the way that `JimSdlGetLongs()` is used, having the string argument be in the middle of the numeric arguments makes this a bit more wordy and error-prone. I could certainly submit it that way, but I think an argument is equally able to be made, since `text` is unique, that the string argument does in fact come first, followed by all the numeric arguments in the same order as several …
> reorder SDL text command help to match parsing

- jim-clock.c
Currently (in the UK, pre-DST, with "now" set to 1711500000):
```
. clock scan {2024-03-31 00:00:00} -format {%F %T} -gmt 0	;# Correct
1711843200
. clock scan {2024-03-31 00:00:00} -format {%F %T} -gmt 1	;# Correct
1711843200
. clock scan {2024-04-01 00:00:00} -format {%F %T} -gmt 0	;# Wrong
1711929600
. clock scan {2024-04-01 00:00:00} -format {%F %T} -gmt 1	;# Correct
1711929600
```
Next week (post-DST, with "now" set to 1712000000):
```
. clock scan {2024-03-31 00:00:00} -format {%F %T} -gmt 0	;# Wrong
1711839600
. clock scan {2024-03-31 00:00:00} -format {%F %T} -gmt 1	;# Correct
1711843200
. clock scan {2024-04-01 00:00:00} -format {%F %T} -gmt 0	;# Correct
1711926000
. clock scan {2024-04-01 00:00:00} -format {%F %T} -gmt 1	;# Correct
1711929600
```
This because tm.tm_isdst is set …
> clock: Fix DST problem in [clock scan] using "-gmt 0"

- jimiocompat.c
I found this while trying to target jimtcl for Classic Mac OS with [Retro68](https://github.com/autc04/Retro68).
> Hide some more umask() calls behind HAVE_UMASK

- jim-json.c
- jim.c
- jim.h
- jsmn/jsmn.c
- jsmn/jsmn.h
- regtest.tcl
- tests/json.test
Better handling of invalid JSON
Preserve line numbers
> Json decode improvements

- initjimsh.tcl
- jim-aio.c
- jim-win32compat.h
- jimiocompat.c
- jimiocompat.h
- make-bootstrap-jim
Now both mingw and msvc are supported
> Allow bootstrap jimsh to build with MSVC on Windows

- jim-aio.c
- jim_tcl.txt
- jimiocompat.h
- jimsh.c
- tclcompat.tcl
- tcltest.tcl
- tests/io.test
This can be necessary on Windows to set stdout and/or stderr to binary output mode
Also adds fconfigure -translation
Note that we don't support all the modes that Tcl does (cr, crlf, lf, auto). Only `binary` and the new option `text` as that maps more directly to the underlying support and we really only have the goal of setting binary mode.
> aio: add support for translation binary|text

- Makefile.in
- auto.def
When building for Windows like:
```
> ./configure \
--host=x86_64-w64-mingw32 \
--build=x86_64-linux-gnu \
--disable-ssl \
--minimal
> make -j install DESTDIR=${PWD}/install
```
The following error is encountered:
```
cp build-jim-ext <PWD>/install/usr/local/bin
cp: cannot stat 'build-jim-ext': No such file or directory
```
The suggested fix changes `buildjimext` variable in `auto.def` to a define and copies `build-jim-ext` only if the define is set.
> build: win32: fix install of `build-jim-ext`

- .gitignore
Ignore *.so and *.dylib files in Git.
See #349
> Add more build generated files to .gitignore
